#spring.datasource.url=jdbc:mysql://${DB_SERVIDOR}:${DB_PUERTO}/${DB_BASE_DATOS}?useSSL=false&serverTimezone=UTC
#spring.datasource.username=${DB_USUARIO}
#spring.datasource.password=${DB_CONTRASENA}

spring.datasource.url=jdbc:mysql://${DB_SERVIDOR:localhost}:${DB_PUERTO:3306}/${DB_BASE_DATOS:agenda_pro}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USUARIO:root}
spring.datasource.password=${DB_CONTRASENA:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USUARIO}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1