#spring.datasource.url=jdbc:mysql://localhost:3306/agenda_pro?serverTimezone=UTC
spring.datasource.url=jdbc:mysql://bx6g24lyfiymhl1s8m9d-mysql.services.clever-cloud.com:3306/bx6g24lyfiymhl1s8m9d?serverTimezone=UTC
spring.datasource.username=uqn8rlwvbnrwm3ym
spring.datasource.password=aD8qI9GQmugxEdBw9nK1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ruizcocera.daniel@loscerros.org
spring.mail.password=uaakbshmicotaqbe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Aumentar el límite de tamaño de subida de archivos (imágenes)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB